/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.ipleiria.tripPlanner.gui.GestaoEtapas;

import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.events.OkAssociarEtapasClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.OkAssociarEtapasClicadoListener;

/**
 *
 * @author DELL
 */
public class AssociarEtapas extends javax.swing.JPanel {
    private List<OkAssociarEtapasClicadoListener> okAssociarEtapasClicadoListener;

    /**
     * Creates new form ReservarAlojamento
     */
    public AssociarEtapas() {
        initComponents();
        this.okAssociarEtapasClicadoListener = new ArrayList<>();
    }
    
    public synchronized void addOkAssociarEtapasClicadoListener(OkAssociarEtapasClicadoListener listener) {
        this.okAssociarEtapasClicadoListener.add(listener);
    }

    public synchronized void removeOkAssociarEtapasClicadoListener(OkAssociarEtapasClicadoListener listener) {
        this.okAssociarEtapasClicadoListener.remove(listener);
    }

    protected synchronized void fireOkAssociarEtapasClicadoEvent() {
        for (OkAssociarEtapasClicadoListener listener : this.okAssociarEtapasClicadoListener) {
            OkAssociarEtapasClicadoEvent evento = new OkAssociarEtapasClicadoEvent(this);
            listener.okAssociarEtapasClicado(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlojamentos = new javax.swing.JLabel();
        lblReservas = new javax.swing.JLabel();
        spAlojamentos = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        spReservas = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        btnAssociar = new javax.swing.JButton();
        btnEliminarAssociacao = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        lblAlojamentos.setText("Participantes");

        lblReservas.setText("Etapa");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spAlojamentos.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spReservas.setViewportView(jList2);

        btnAssociar.setText(">>");

        btnEliminarAssociacao.setText("<<");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblAlojamentos)
                        .addGap(172, 172, 172)
                        .addComponent(lblReservas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spAlojamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAssociar)
                            .addComponent(btnEliminarAssociacao))
                        .addGap(37, 37, 37)
                        .addComponent(spReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnOk)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar)))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReservas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlojamentos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spAlojamentos)
                            .addComponent(spReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAssociar)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminarAssociacao)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.fireOkAssociarEtapasClicadoEvent();
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarAssociacao;
    private javax.swing.JButton btnOk;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JLabel lblAlojamentos;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JScrollPane spAlojamentos;
    private javax.swing.JScrollPane spReservas;
    // End of variables declaration//GEN-END:variables
}
