/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.ipleiria.tripPlanner.gui.GestaoEtapas;

import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.events.InserirEtapasClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.InserirEtapasClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.OkInserirEtapasClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.OkInserirEtapasClicadoListener;

/**
 *
 * @author DELL
 */
public class InserirEditarEtapa extends javax.swing.JPanel {
    private List<OkInserirEtapasClicadoListener> okInserirEtapasClicadoListener;
    /**
     * Creates new form InserirEtapa
     */
    public InserirEditarEtapa() {
        initComponents();
        this.okInserirEtapasClicadoListener = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLocalidadeInicio = new javax.swing.JLabel();
        lblLocalidadeFinal = new javax.swing.JLabel();
        lblListaLocalidades = new javax.swing.JLabel();
        lblDistanciaTotal = new javax.swing.JLabel();
        lblAltitudeAcumulada = new javax.swing.JLabel();
        lblAltitudeMaxima = new javax.swing.JLabel();
        lblAltitudeMinima = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfLocalidadeInicio = new javax.swing.JTextField();
        tfLocalidadeFinal = new javax.swing.JTextField();
        spListaLocalidades = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        tfDistanciaTotal = new javax.swing.JTextField();
        tfAltitudeAcumulada = new javax.swing.JTextField();
        tfAltitudeMaxima = new javax.swing.JTextField();
        tfAltitudeMinima = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        lblLocalidadeInicio.setText("Localidade Início:");

        lblLocalidadeFinal.setText("Localidade Final:");

        lblListaLocalidades.setText("Lista Localidades:");

        lblDistanciaTotal.setText("Distância Total:");

        lblAltitudeAcumulada.setText("Altitude Acumulada:");

        lblAltitudeMaxima.setText("Altitude Máxima:");

        lblAltitudeMinima.setText("Altitude Mínima:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spListaLocalidades.setViewportView(jList1);

        tfAltitudeAcumulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAltitudeAcumuladaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblListaLocalidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spListaLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblLocalidadeFinal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfLocalidadeFinal))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblLocalidadeInicio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfLocalidadeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(444, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltitudeMinima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAltitudeMinima))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDistanciaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDistanciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltitudeAcumulada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAltitudeAcumulada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltitudeMaxima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAltitudeMaxima)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadeInicio)
                    .addComponent(tfLocalidadeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadeFinal)
                    .addComponent(tfLocalidadeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaLocalidades)
                    .addComponent(spListaLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistanciaTotal)
                    .addComponent(tfDistanciaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltitudeAcumulada)
                    .addComponent(tfAltitudeAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltitudeMaxima)
                    .addComponent(tfAltitudeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltitudeMinima)
                    .addComponent(tfAltitudeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfAltitudeAcumuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAltitudeAcumuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAltitudeAcumuladaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.fireOkInserirEtapasClicadoEvent();
    }//GEN-LAST:event_btnOkActionPerformed

    public synchronized void addOkInserirEtapasClicadoListener(OkInserirEtapasClicadoListener listener) {
        this.okInserirEtapasClicadoListener.add(listener);
    }

    public synchronized void removeOkInserirEtapasClicadoListener(OkInserirEtapasClicadoListener listener) {
        this.okInserirEtapasClicadoListener.remove(listener);
    }

    protected synchronized void fireOkInserirEtapasClicadoEvent() {
        for (OkInserirEtapasClicadoListener listener : this.okInserirEtapasClicadoListener) {
            OkInserirEtapasClicadoEvent evento = new OkInserirEtapasClicadoEvent(this);
            listener.okInserirEtapasClicado(evento);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JList jList1;
    private javax.swing.JLabel lblAltitudeAcumulada;
    private javax.swing.JLabel lblAltitudeMaxima;
    private javax.swing.JLabel lblAltitudeMinima;
    private javax.swing.JLabel lblDistanciaTotal;
    private javax.swing.JLabel lblListaLocalidades;
    private javax.swing.JLabel lblLocalidadeFinal;
    private javax.swing.JLabel lblLocalidadeInicio;
    private javax.swing.JScrollPane spListaLocalidades;
    private javax.swing.JTextField tfAltitudeAcumulada;
    private javax.swing.JTextField tfAltitudeMaxima;
    private javax.swing.JTextField tfAltitudeMinima;
    private javax.swing.JTextField tfDistanciaTotal;
    private javax.swing.JTextField tfLocalidadeFinal;
    private javax.swing.JTextField tfLocalidadeInicio;
    // End of variables declaration//GEN-END:variables
}
