/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.ipleiria.tripPlanner.gui.GestaoAlojamento;

import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoListener;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoListener;

/**
 *
 * @author DELL
 */
public class CriarEditarAlojamento extends javax.swing.JPanel {

     private List<ConfirmarClicadoAlojamentoListener> confirmarClicadoAlojamentoListener;
    /**
     * Creates new form CriarAlojamento
     */
    public CriarEditarAlojamento() {
        initComponents();
        
        this.confirmarClicadoAlojamentoListener = new ArrayList<>();
    }

     public synchronized void addConfirmarClicadoAlojamentoistener(ConfirmarClicadoAlojamentoListener listener){
        this.confirmarClicadoAlojamentoListener.add(listener);
    }
    
    public synchronized void removeConfirmarClicadoAlojamentoListener(ConfirmarClicadoAlojamentoListener listener){
        this.confirmarClicadoAlojamentoListener.remove(listener);
    }

    protected synchronized void fireConfirmarClicadoAlojamentoEvent(){
        for(ConfirmarClicadoAlojamentoListener listener : this.confirmarClicadoAlojamentoListener){
        ConfirmarClicadoAlojamentoEvent evento = new ConfirmarClicadoAlojamentoEvent(this);
        listener.confirmarClicadoAlojamento(evento);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        lblDesignacao = new javax.swing.JLabel();
        tfDesignacao = new javax.swing.JTextField();
        lblGPS = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        tfLongitude = new javax.swing.JTextField();
        lblLatitude = new javax.swing.JLabel();
        tfLatitude = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        rbAlbergue = new javax.swing.JRadioButton();
        rbPensao = new javax.swing.JRadioButton();
        rbHostal = new javax.swing.JRadioButton();
        rbHotel = new javax.swing.JRadioButton();
        rbOutros = new javax.swing.JRadioButton();
        lblQuartos = new javax.swing.JLabel();
        spQuartos = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        lblHorariodeFuncionamento = new javax.swing.JLabel();
        spHorariodeFuncionamento = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();
        btnCheckin_out = new javax.swing.JLabel();
        lblContactos = new javax.swing.JLabel();
        lblMorada = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        tfCheckin_out = new javax.swing.JTextField();
        tfContactos = new javax.swing.JTextField();
        tfMorada = new javax.swing.JTextField();
        spObservacoes = new javax.swing.JScrollPane();
        lblHoráriodeFuncionamento = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        lblDesignacao.setText("Designação:");

        lblGPS.setText("GPS:");

        lblLongitude.setText("Longitude:");

        lblLatitude.setText("Latitude:");

        lblTipo.setText("Tipo:");

        buttonGroup2.add(rbAlbergue);
        rbAlbergue.setText("Albergue");

        buttonGroup2.add(rbPensao);
        rbPensao.setText("Pensão");

        buttonGroup2.add(rbHostal);
        rbHostal.setText("Hostal");

        buttonGroup2.add(rbHotel);
        rbHotel.setText("Hotel");

        buttonGroup2.add(rbOutros);
        rbOutros.setText("Outros");

        lblQuartos.setText("Quartos:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spQuartos.setViewportView(jList1);

        lblHorariodeFuncionamento.setText("Horário de Funcionamento:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        spHorariodeFuncionamento.setViewportView(jTextArea1);

        btnAdicionar.setText("Adicionar");

        btnCheckin_out.setText("Check in / out:");

        lblContactos.setText("Contactos:");

        lblMorada.setText("Morada:");

        lblObservacoes.setText("Observações:");

        lblHoráriodeFuncionamento.setColumns(20);
        lblHoráriodeFuncionamento.setRows(5);
        spObservacoes.setViewportView(lblHoráriodeFuncionamento);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAlbergue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPensao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbHostal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOutros))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLongitude)
                        .addGap(2, 2, 2)
                        .addComponent(tfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLatitude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuartos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHorariodeFuncionamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spHorariodeFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDesignacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDesignacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCheckin_out)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCheckin_out, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblObservacoes)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactos)
                                    .addComponent(lblMorada))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(spObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesignacao)
                    .addComponent(tfDesignacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPS)
                    .addComponent(lblLongitude)
                    .addComponent(tfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLatitude)
                    .addComponent(tfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(rbAlbergue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPensao)
                        .addComponent(rbHostal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHotel)
                    .addComponent(rbOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnCancelar))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuartos)
                            .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorariodeFuncionamento)
                            .addComponent(spHorariodeFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckin_out)
                            .addComponent(tfCheckin_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactos)
                            .addComponent(tfContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMorada)
                            .addComponent(tfMorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblObservacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
         this.fireConfirmarClicadoAlojamentoEvent();
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCheckin_out;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JList jList1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblContactos;
    private javax.swing.JLabel lblDesignacao;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblHorariodeFuncionamento;
    private javax.swing.JTextArea lblHoráriodeFuncionamento;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMorada;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbAlbergue;
    private javax.swing.JRadioButton rbHostal;
    private javax.swing.JRadioButton rbHotel;
    private javax.swing.JRadioButton rbOutros;
    private javax.swing.JRadioButton rbPensao;
    private javax.swing.JScrollPane spHorariodeFuncionamento;
    private javax.swing.JScrollPane spObservacoes;
    private javax.swing.JScrollPane spQuartos;
    private javax.swing.JTextField tfCheckin_out;
    private javax.swing.JTextField tfContactos;
    private javax.swing.JTextField tfDesignacao;
    private javax.swing.JTextField tfLatitude;
    private javax.swing.JTextField tfLongitude;
    private javax.swing.JTextField tfMorada;
    // End of variables declaration//GEN-END:variables
}
