/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.ipleiria.tripPlanner.gui.GestaoAlojamento;

import pt.ipleiria.tripPlanner.gui.Models.Alojamento;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Quarto;
import pt.ipleiria.tripPlanner.gui.Utils.CellRendererQuartos;
import pt.ipleiria.tripPlanner.gui.events.AdicionarQuartoClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.AdicionarQuartoClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoListener;

/**
 *
 * @author DELL
 */
public class CriarEditarAlojamento extends javax.swing.JPanel {

    private List<ConfirmarClicadoAlojamentoListener> confirmarClicadoAlojamentoListener;
    private List<AdicionarQuartoClicadoListener> adicionarQuartoClidadoListerner;

    /**
     * Creates new form CriarAlojamento
     */
    public CriarEditarAlojamento() {
        initComponents();

        this.confirmarClicadoAlojamentoListener = new ArrayList<>();
        this.adicionarQuartoClidadoListerner = new ArrayList<>();
        jList1.setCellRenderer((ListCellRenderer) new CellRendererQuartos());
        actualizarListaQuartos();
    }

    public synchronized void addConfirmarClicadoAlojamentoListener(ConfirmarClicadoAlojamentoListener listener) {
        this.confirmarClicadoAlojamentoListener.add(listener);
    }

    public synchronized void removeConfirmarClicadoAlojamentoListener(ConfirmarClicadoAlojamentoListener listener) {
        this.confirmarClicadoAlojamentoListener.remove(listener);
    }

    protected synchronized void fireConfirmarClicadoAlojamentoEvent() {
        for (ConfirmarClicadoAlojamentoListener listener : this.confirmarClicadoAlojamentoListener) {
            ConfirmarClicadoAlojamentoEvent evento = new ConfirmarClicadoAlojamentoEvent(this);
            listener.confirmarClicadoAlojamento(evento);
        }
    }

    public synchronized void addAdicionarQuartoClicado(AdicionarQuartoClicadoListener listener) {
        this.adicionarQuartoClidadoListerner.add(listener);
    }

    public synchronized void removeAdicionarQuartoClicado(AdicionarQuartoClicadoListener listener) {
        this.adicionarQuartoClidadoListerner.remove(listener);
    }

    protected synchronized void fireAdicionarQuartoClicadoEvent() {
        for (AdicionarQuartoClicadoListener listener : this.adicionarQuartoClidadoListerner) {
            AdicionarQuartoClicadoEvent evento = new AdicionarQuartoClicadoEvent(this);
            listener.adicionarQuartoClicado(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        rbAlbergue = new javax.swing.JRadioButton();
        tfLongitude = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        tfLatitude = new javax.swing.JTextField();
        lblLatitude = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        lblDesignacao = new javax.swing.JLabel();
        tfDesignacao = new javax.swing.JTextField();
        rbHostal = new javax.swing.JRadioButton();
        rbOutros = new javax.swing.JRadioButton();
        rbPensao = new javax.swing.JRadioButton();
        rbHotel = new javax.swing.JRadioButton();
        lblErrD = new javax.swing.JLabel();
        lblErrGPS = new javax.swing.JLabel();
        lblErrTipo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spObservacoes = new javax.swing.JScrollPane();
        lblHoráriodeFuncionamento = new javax.swing.JTextArea();
        tfMorada = new javax.swing.JTextField();
        tfContactos = new javax.swing.JTextField();
        tfCheckin = new javax.swing.JTextField();
        lblContactos = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        lblMorada = new javax.swing.JLabel();
        btnCheckin_out = new javax.swing.JLabel();
        spHorariodeFuncionamento = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblHorariodeFuncionamento = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JLabel();
        tfCheckout = new javax.swing.JTextField();
        lblErrHorarioFunc = new javax.swing.JLabel();
        lblErrCheckin = new javax.swing.JLabel();
        lblErrCheckout = new javax.swing.JLabel();
        lblErrContactos = new javax.swing.JLabel();
        lblErrMorada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        spQuartos = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        lblQuartos = new javax.swing.JLabel();
        lblErrQuarto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Designação"));
        jPanel1.setToolTipText("");

        lblTipo.setText("*Tipo:");

        buttonGroup2.add(rbAlbergue);
        rbAlbergue.setText("Albergue");

        lblLongitude.setText("Longitude:");

        lblLatitude.setText("Latitude:");

        lblGPS.setText("*GPS:");

        lblDesignacao.setText("*Designação:");

        buttonGroup2.add(rbHostal);
        rbHostal.setText("Hostal");

        buttonGroup2.add(rbOutros);
        rbOutros.setText("Outros");

        buttonGroup2.add(rbPensao);
        rbPensao.setText("Pensão");

        buttonGroup2.add(rbHotel);
        rbHotel.setText("Hotel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbAlbergue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbPensao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbHostal))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbHotel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbOutros))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGPS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblLongitude)
                                        .addGap(2, 2, 2)
                                        .addComponent(tfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblLatitude)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfLatitude))
                                    .addComponent(lblErrGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDesignacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDesignacao))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblErrTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesignacao)
                    .addComponent(tfDesignacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrD, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPS)
                    .addComponent(lblLongitude)
                    .addComponent(tfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLatitude)
                    .addComponent(tfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipo)
                        .addComponent(rbAlbergue))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbPensao)
                        .addComponent(rbHostal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHotel)
                    .addComponent(rbOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrTipo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contactos"));

        lblHoráriodeFuncionamento.setColumns(20);
        lblHoráriodeFuncionamento.setRows(5);
        spObservacoes.setViewportView(lblHoráriodeFuncionamento);

        lblContactos.setText("*Contactos:");

        lblObservacoes.setText("Observações:");

        lblMorada.setText("*Morada:");

        btnCheckin_out.setText("*Check in:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        spHorariodeFuncionamento.setViewportView(jTextArea1);

        lblHorariodeFuncionamento.setText("*Horário de Funcionamento:");

        btnCheckout.setText("*Check out:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblErrHorarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCheckin_out)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblErrCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfCheckin)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCheckout)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfContactos)
                                            .addComponent(tfCheckout)
                                            .addComponent(lblErrContactos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfMorada)
                                            .addComponent(lblErrMorada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactos)
                                    .addComponent(lblMorada)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addComponent(spObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblObservacoes)))
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblHorariodeFuncionamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spHorariodeFuncionamento)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHorariodeFuncionamento)
                    .addComponent(spHorariodeFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrHorarioFunc)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckin_out)
                    .addComponent(tfCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrCheckin)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout)
                    .addComponent(tfCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrCheckout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactos)
                    .addComponent(tfContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrContactos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMorada)
                    .addComponent(tfMorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrMorada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quartos"));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spQuartos.setViewportView(jList1);

        lblQuartos.setText("*Quartos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar))
                    .addComponent(lblErrQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuartos)
                    .addComponent(btnAdicionar)
                    .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrQuarto)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("Alojamento");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(97, 97, 97))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)))
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        adicionarAlojamento();

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        this.fireAdicionarQuartoClicadoEvent();
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCheckin_out;
    private javax.swing.JLabel btnCheckout;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblContactos;
    private javax.swing.JLabel lblDesignacao;
    private javax.swing.JLabel lblErrCheckin;
    private javax.swing.JLabel lblErrCheckout;
    private javax.swing.JLabel lblErrContactos;
    private javax.swing.JLabel lblErrD;
    private javax.swing.JLabel lblErrGPS;
    private javax.swing.JLabel lblErrHorarioFunc;
    private javax.swing.JLabel lblErrMorada;
    private javax.swing.JLabel lblErrQuarto;
    private javax.swing.JLabel lblErrTipo;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblHorariodeFuncionamento;
    private javax.swing.JTextArea lblHoráriodeFuncionamento;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMorada;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbAlbergue;
    private javax.swing.JRadioButton rbHostal;
    private javax.swing.JRadioButton rbHotel;
    private javax.swing.JRadioButton rbOutros;
    private javax.swing.JRadioButton rbPensao;
    private javax.swing.JScrollPane spHorariodeFuncionamento;
    private javax.swing.JScrollPane spObservacoes;
    private javax.swing.JScrollPane spQuartos;
    private javax.swing.JTextField tfCheckin;
    private javax.swing.JTextField tfCheckout;
    private javax.swing.JTextField tfContactos;
    private javax.swing.JTextField tfDesignacao;
    private javax.swing.JTextField tfLatitude;
    private javax.swing.JTextField tfLongitude;
    private javax.swing.JTextField tfMorada;
    // End of variables declaration//GEN-END:variables

    private void adicionarAlojamento() {
        lblErrCheckin.setText("");
        lblErrCheckin.setForeground(Color.red);
        lblErrCheckout.setText("");
        lblErrCheckout.setForeground(Color.red);
        lblErrContactos.setText("");
        lblErrContactos.setForeground(Color.red);
        lblErrD.setText("");
        lblErrD.setForeground(Color.red);
        lblErrGPS.setText("");
        lblErrGPS.setForeground(Color.red);
        lblErrHorarioFunc.setText("");
        lblErrHorarioFunc.setForeground(Color.red);
        lblErrMorada.setText("");
        lblErrMorada.setForeground(Color.red);
        lblErrQuarto.setText("");
        lblErrQuarto.setForeground(Color.red);
        lblErrTipo.setText("");
        lblErrTipo.setForeground(Color.red);

        boolean isOk = true;
        if (tfDesignacao.getText().isEmpty()) {
            lblErrD.setText("Insira uma Designação.");
            isOk = false;
        }
        if (tfLongitude.getText().isEmpty() && tfLatitude.getText().isEmpty()) {
            lblErrGPS.setText("Insira as coordenadas GPS.");
            isOk = false;
        }
        if (!rbAlbergue.isSelected() && !rbHostal.isSelected() && !rbHotel.isSelected() && !rbOutros.isSelected() && !rbPensao.isSelected()) {
            lblErrTipo.setText("Selecione um tipo de alojamento.");
            isOk = false;
        }
        // QUARTOS!!
        if (jList1.getSelectedIndex() < 0) {
            lblErrQuarto.setText("Escolha um quarto");
            isOk = false;
        }
        if (jTextArea1.getText().isEmpty()) {
            lblErrHorarioFunc.setText("Insira o Horário de Funcionamento.");
            isOk = false;
        }
        if (tfCheckin.getText().isEmpty()) {
            lblErrCheckin.setText("Insira Check in.");
            isOk = false;

        }
        if (tfCheckout.getText().isEmpty()) {
            lblErrCheckout.setText("Insira Check out.");
            isOk = false;
        }
        if (tfContactos.getText().isEmpty()) {
            lblErrContactos.setText("Insira os Contactos.");
            isOk = false;
        }
        if (tfMorada.getText().isEmpty()) {
            lblErrMorada.setText("Insira uma Morada.");
            isOk = false;
        }

        if (isOk) {
            DefaultListModel<Quarto> model = (DefaultListModel<Quarto>) jList1.getModel();
            ArrayList<Quarto> quartos = new ArrayList<>();
            for (int index : jList1.getSelectedIndices()) {
                Quarto q = model.elementAt(index);
                quartos.add(q);
            }
            String tipo = null;
            if (rbAlbergue.isSelected()) {
                tipo = "Albergue";
            } else if (rbHostal.isSelected()) {
                tipo = "Hostal";
            } else if (rbHotel.isSelected()) {
                tipo = "Hotel";
            } else if (rbOutros.isSelected()) {
                tipo = "Outros";
            } else if (rbPensao.isSelected()) {
                tipo = "Pensao";
            }
            Alojamento alojamento = new Alojamento(tfDesignacao.getText(), tfLongitude.getText(), tfLatitude.getText(), tipo, quartos, jTextArea1.getText(), tfCheckin.getText(), tfCheckout.getText(), tfContactos.getText(), tfMorada.getText());
            DadosAplicacao.getInstance().addAlojamento(alojamento);
            JOptionPane.showMessageDialog(this, "Alojamento Inserida com Sucesso!", "Inserção Realizada Com Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.fireConfirmarClicadoAlojamentoEvent();
        }
    }

    public void actualizarListaQuartos() {
        DefaultListModel<Quarto> model = new DefaultListModel<>();
        for (Quarto quarto : DadosAplicacao.getInstance().getQuartos()) {
            model.addElement(quarto);
        }
        jList1.setModel(model);
    }
}
