/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.ipleiria.tripPlanner.gui.GestaoAlojamento;

import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoAlojamentoListener;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoListener;

/**
 *
 * @author DELL
 */
public class MostrarAlojamento extends javax.swing.JPanel {

    private List<ConfirmarClicadoAlojamentoListener> confirmarClicadoAlojamentoListener;
    /**
     * Creates new form CriarAlojamento
     */
    public MostrarAlojamento() {
        initComponents();
        
        this.confirmarClicadoAlojamentoListener = new ArrayList<>();
    }
    
 public synchronized void addConfirmarClicadoAlojamentoistener(ConfirmarClicadoAlojamentoListener listener){
        this.confirmarClicadoAlojamentoListener.add(listener);
    }
    
    public synchronized void removeConfirmarClicadoAlojamentoListener(ConfirmarClicadoAlojamentoListener listener){
        this.confirmarClicadoAlojamentoListener.remove(listener);
    }

    protected synchronized void fireConfirmarClicadoAlojamentoEvent(){
        for(ConfirmarClicadoAlojamentoListener listener : this.confirmarClicadoAlojamentoListener){
        ConfirmarClicadoAlojamentoEvent evento = new ConfirmarClicadoAlojamentoEvent(this);
        listener.confirmarClicadoAlojamento(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        lblDesignacao = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        rbAlbergue = new javax.swing.JRadioButton();
        rbPensao = new javax.swing.JRadioButton();
        rbHostal = new javax.swing.JRadioButton();
        rbHotel = new javax.swing.JRadioButton();
        rbOutros = new javax.swing.JRadioButton();
        lblQuartos = new javax.swing.JLabel();
        spQuartos = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        lblHorariodeFuncionamento = new javax.swing.JLabel();
        btnCheckin_out = new javax.swing.JLabel();
        lblContactos = new javax.swing.JLabel();
        lblMorada = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMostrarDesignacao = new javax.swing.JLabel();
        lblMostrarLongitude = new javax.swing.JLabel();
        lblMostrarHorárioFuncionamento = new javax.swing.JLabel();
        lblMostraCheckin_out = new javax.swing.JLabel();
        lblMostrarContactos = new javax.swing.JLabel();
        lblMostrarMorada = new javax.swing.JLabel();
        lblMostrarObservacoes = new javax.swing.JLabel();
        lblMostrarLatitude = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        lblDesignacao.setText("Designação:");

        lblGPS.setText("GPS:");

        lblLongitude.setText("Longitude:");

        lblLatitude.setText("Latitude:");

        lblTipo.setText("Tipo:");

        buttonGroup2.add(rbAlbergue);
        rbAlbergue.setText("Albergue");

        buttonGroup2.add(rbPensao);
        rbPensao.setText("Pensão");

        buttonGroup2.add(rbHostal);
        rbHostal.setText("Hostal");

        buttonGroup2.add(rbHotel);
        rbHotel.setText("Hotel");

        buttonGroup2.add(rbOutros);
        rbOutros.setText("Outros");

        lblQuartos.setText("Quartos:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spQuartos.setViewportView(jList1);

        lblHorariodeFuncionamento.setText("Horário de Funcionamento:");

        btnCheckin_out.setText("Check in / out:");

        lblContactos.setText("Contactos:");

        lblMorada.setText("Morada:");

        lblObservacoes.setText("Observações:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLongitude)
                        .addGap(76, 76, 76)
                        .addComponent(lblMostrarLongitude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLatitude)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMostrarLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAlbergue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbPensao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbHostal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbHotel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOutros))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDesignacao)
                        .addGap(83, 83, 83)
                        .addComponent(lblMostrarDesignacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblMostraCheckin_out))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(lblMostrarMorada))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(192, 192, 192)
                                        .addComponent(lblMostrarContactos))
                                    .addComponent(lblHorariodeFuncionamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMostrarHorárioFuncionamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblQuartos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckin_out)
                            .addComponent(lblObservacoes)
                            .addComponent(lblMorada)
                            .addComponent(lblContactos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMostrarObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesignacao)
                            .addComponent(lblMostrarDesignacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGPS)
                            .addComponent(lblLongitude)
                            .addComponent(lblLatitude)
                            .addComponent(lblMostrarLongitude)
                            .addComponent(lblMostrarLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo)
                            .addComponent(rbAlbergue)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbPensao)
                                .addComponent(rbHostal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHotel)
                            .addComponent(rbOutros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuartos)
                                    .addComponent(spQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(lblHorariodeFuncionamento))
                            .addComponent(lblMostrarHorárioFuncionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckin_out)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContactos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMorada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblObservacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMostrarObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnCancelar))))
                .addGap(23, 23, 23)
                .addComponent(lblMostraCheckin_out)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostrarContactos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostrarMorada)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.fireConfirmarClicadoAlojamentoEvent();
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnCheckin_out;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JList jList1;
    private javax.swing.JLabel lblContactos;
    private javax.swing.JLabel lblDesignacao;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblHorariodeFuncionamento;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMorada;
    private javax.swing.JLabel lblMostraCheckin_out;
    private javax.swing.JLabel lblMostrarContactos;
    private javax.swing.JLabel lblMostrarDesignacao;
    private javax.swing.JLabel lblMostrarHorárioFuncionamento;
    private javax.swing.JLabel lblMostrarLatitude;
    private javax.swing.JLabel lblMostrarLongitude;
    private javax.swing.JLabel lblMostrarMorada;
    private javax.swing.JLabel lblMostrarObservacoes;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbAlbergue;
    private javax.swing.JRadioButton rbHostal;
    private javax.swing.JRadioButton rbHotel;
    private javax.swing.JRadioButton rbOutros;
    private javax.swing.JRadioButton rbPensao;
    private javax.swing.JScrollPane spQuartos;
    // End of variables declaration//GEN-END:variables
}
