/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.ipleiria.tripPlanner.gui.GestaoViagens;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Participante;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarAssociacaoViagensEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarAssociacaoViagensListener;

/**
 *
 * @author DELL
 */
public class AssociarViagens extends javax.swing.JPanel {

    private List<ConfirmarAssociacaoViagensListener> confirmarAssociacaoViagensListener;

    private ArrayList<Participante> participantesModelList;
    private DefaultListModel<Participante> modelP;

    private ArrayList<Participante> associadosModelList;
    private DefaultListModel<Participante> modelA;

    /**
     * Creates new form ReservarAlojamento
     */
    public AssociarViagens() {
        initComponents();
        this.confirmarAssociacaoViagensListener = new ArrayList<>();

        participantesModelList = new ArrayList<>();
        modelP = new DefaultListModel<>();

        associadosModelList = new ArrayList<>();
        modelA = new DefaultListModel<>();

        setModel();

        lblAvisoA.setVisible(false);
        lblAvisoP.setVisible(false);
    }

    /*
    
     private ArrayList<Etapa> etapasModelListS;
     private DefaultListModel<Etapa> modelES;
    
     adicionar
    
     etapasModelListS = (ArrayList<Etapa>) lstEtapasP.getSelectedValuesList();
     modelES.clear();
     for (Etapa e : etapasModelListS) {
     modelES.addElement(e);
     }
     lstEtapas.setModel(modelES);

     pEtapas.setVisible(false);
    
     remover
    
     DefaultListModel m = (DefaultListModel) lstEtapas.getModel();
     int i = lstEtapas.getSelectedIndex();
     if ((i + 1) != -1) {
     m.remove(i);
     }
    
     */
    public synchronized void addConfirmarAssociacaoViagensListener(ConfirmarAssociacaoViagensListener listener) {
        this.confirmarAssociacaoViagensListener.add(listener);
    }

    public synchronized void removeConfirmarAssociacaoViagensListener(ConfirmarAssociacaoViagensListener listener) {
        this.confirmarAssociacaoViagensListener.remove(listener);
    }

    protected synchronized void fireConfirmarAssociacaoViagensEvent() {
        for (ConfirmarAssociacaoViagensListener listener : this.confirmarAssociacaoViagensListener) {
            ConfirmarAssociacaoViagensEvent evento = new ConfirmarAssociacaoViagensEvent(this);
            listener.confirmarAssociacaoViagens(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEliminarAssociacaoVarios = new javax.swing.JButton();
        btnAssociarVarios = new javax.swing.JButton();
        spViagens = new javax.swing.JScrollPane();
        lstAssociados = new javax.swing.JList();
        spParticipantes = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        lblViagens = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();
        btnAssociarUm = new javax.swing.JButton();
        btnEliminarAssociacaoUm = new javax.swing.JButton();
        lblAvisoP = new javax.swing.JLabel();
        lblAvisoA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        btnOk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarAssociacaoVarios.setText("<<");
        btnEliminarAssociacaoVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAssociacaoVariosActionPerformed(evt);
            }
        });

        btnAssociarVarios.setText(">>");
        btnAssociarVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarVariosActionPerformed(evt);
            }
        });

        lstAssociados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spViagens.setViewportView(lstAssociados);

        lstParticipantes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spParticipantes.setViewportView(lstParticipantes);

        lblViagens.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblViagens.setText("Associados:");

        lblParticipantes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblParticipantes.setText("Participantes:");

        btnAssociarUm.setText(">");
        btnAssociarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarUmActionPerformed(evt);
            }
        });

        btnEliminarAssociacaoUm.setText("<");
        btnEliminarAssociacaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAssociacaoUmActionPerformed(evt);
            }
        });

        lblAvisoP.setText("jLabel2");

        lblAvisoA.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAssociarVarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarAssociacaoVarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssociarUm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarAssociacaoUm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblParticipantes)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblViagens)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvisoA)
                            .addComponent(spViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAvisoP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnAssociarUm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAssociarVarios)
                                .addGap(27, 27, 27)
                                .addComponent(btnEliminarAssociacaoUm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarAssociacaoVarios))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblParticipantes)
                                    .addComponent(lblViagens))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(spViagens)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvisoP)
                    .addComponent(lblAvisoA))
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setText("Associar Participante a Viagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        GestaodeViagens.getInstance().getSelectedViagem();
        this.fireConfirmarAssociacaoViagensEvent();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAssociarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarUmActionPerformed

        if (lstParticipantes.getSelectedValuesList().size() != 1) {
            lblAvisoP.setText("Apenas pode ter um participante selecionado");
        } else {
            modelA.addElement((Participante) lstParticipantes.getSelectedValue());
            lstParticipantes.setModel(modelA);
        }
    }//GEN-LAST:event_btnAssociarUmActionPerformed

    private void btnAssociarVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarVariosActionPerformed
        if (lstParticipantes.getSelectedValuesList().isEmpty()) {
            lblAvisoP.setText("Não tem nenhum participante selecionado");
        } else {
            associadosModelList = (ArrayList<Participante>) lstParticipantes.getSelectedValuesList();
            for (Participante p : associadosModelList) {
                modelP.addElement(p);
            }
        }
    }//GEN-LAST:event_btnAssociarVariosActionPerformed

    private void btnEliminarAssociacaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAssociacaoUmActionPerformed
        if (lstParticipantes.getSelectedValuesList().size() != 1) {
            lblAvisoP.setText("Apenas pode ter um participante selecionado");
        } else {
            modelP.removeElement(lstAssociados.getSelectedValue());
            lstAssociados.setModel(modelP);
        }
    }//GEN-LAST:event_btnEliminarAssociacaoUmActionPerformed

    private void btnEliminarAssociacaoVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAssociacaoVariosActionPerformed
        if (lstParticipantes.getSelectedValuesList().isEmpty()) {
            lblAvisoP.setText("Não tem nenhum participante selecionado");
        } else {
            associadosModelList = (ArrayList<Participante>) lstAssociados.getSelectedValuesList();
            for (Participante p : associadosModelList) {
                modelA.removeElement(p);
            }
            lstAssociados.setModel(modelA);
        }
    }//GEN-LAST:event_btnEliminarAssociacaoVariosActionPerformed

    private void setModel() {
        participantesModelList = DadosAplicacao.getInstance().getParticipantes();
        modelP.clear();
        for (Participante p : participantesModelList) {
            modelP.addElement(p);
        }
        lstParticipantes.setModel(modelP);

        modelA.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociarUm;
    private javax.swing.JButton btnAssociarVarios;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarAssociacaoUm;
    private javax.swing.JButton btnEliminarAssociacaoVarios;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvisoA;
    private javax.swing.JLabel lblAvisoP;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblViagens;
    private javax.swing.JList lstAssociados;
    private javax.swing.JList lstParticipantes;
    private javax.swing.JScrollPane spParticipantes;
    private javax.swing.JScrollPane spViagens;
    // End of variables declaration//GEN-END:variables

}
