package pt.ipleiria.tripPlanner.gui.GestaoViagens;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.GestaoEtapas.*;
import pt.ipleiria.tripPlanner.gui.GestaoLocalidades.*;
import pt.ipleiria.tripPlanner.gui.cenario.*;
import pt.ipleiria.tripPlanner.gui.events.AssociarViagensClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.AssociarViagensClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.InserirViagemClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.InserirViagemClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.LoginEfetuadoEvent;
import pt.ipleiria.tripPlanner.gui.events.LoginEfetuadoListener;
import pt.ipleiria.tripPlanner.gui.events.VoltarMenuPrincipalListener;
import pt.ipleiria.tripPlanner.gui.events.VoltarMenuPrincipalEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class GestaodeViagens extends javax.swing.JPanel {
    private List<InserirViagemClicadoListener> inserirViagemClicadoListener;
    private List<VoltarMenuPrincipalListener> voltarMenuPrincipalListener;
    private List<AssociarViagensClicadoListener> associarViagensClicadoListener;
    private LinkedList<Viagem> viagens;
    /**
     * Creates new form GestãodeCenáriodeAlojamento
     */
    public GestaodeViagens() {
        initComponents();        
        this.inserirViagemClicadoListener = new ArrayList<>();
        this.voltarMenuPrincipalListener = new ArrayList<>();
        this.associarViagensClicadoListener = new ArrayList<>();
    }
    
      public synchronized void addInserirViagemClicadoListener(InserirViagemClicadoListener listener){
        this.inserirViagemClicadoListener.add(listener);
    }
    
    public synchronized void removeInserirViagemClicadoListener(InserirViagemClicadoListener listener){
        this.inserirViagemClicadoListener.remove(listener);
    }

    protected synchronized void fireInserirViagemClicadoListener(){
        for(InserirViagemClicadoListener listener : this.inserirViagemClicadoListener){
        InserirViagemClicadoEvent evento = new InserirViagemClicadoEvent(this);
        listener.inserirViagemClicado(evento);
        }
    }    
       public synchronized void addVoltarMenuPrincipalListener(VoltarMenuPrincipalListener listener){
        this.voltarMenuPrincipalListener.add(listener);
    }
    
    public synchronized void removeVoltarMenuPrincipalListener(VoltarMenuPrincipalListener listener){
        this.voltarMenuPrincipalListener.remove(listener);
    }

    protected synchronized void fireVoltarMenuPrincipalEvent(){
        for(VoltarMenuPrincipalListener listener : this.voltarMenuPrincipalListener){
        VoltarMenuPrincipalEvent evento = new VoltarMenuPrincipalEvent(this);
        listener.voltarMenuPrincipal(evento);
        }
    }
    
     public synchronized void addAssociarViagensClicadoListener(AssociarViagensClicadoListener listener){
        this.associarViagensClicadoListener.add(listener);
    }
    
    public synchronized void removeAssociarViagensClicadoListener(AssociarViagensClicadoListener listener){
        this.associarViagensClicadoListener.remove(listener);
    }

    protected synchronized void fireAssociarViagensClicadoEvent(){
        for(AssociarViagensClicadoListener listener : this.associarViagensClicadoListener){
        AssociarViagensClicadoEvent evento = new AssociarViagensClicadoEvent(this);
        listener.associarViagensClicado(evento);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        btnCriar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        tfPesquisar = new javax.swing.JTextField();
        lblLocalidades = new javax.swing.JLabel();
        btnAssociar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/Inserir1.png"))); // NOI18N
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/eliminar1.png"))); // NOI18N

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/editar.png"))); // NOI18N

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/lupa.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/back-trans.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        tfPesquisar.setText("Pesquisar");

        lblLocalidades.setText("Viagens");

        btnAssociar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/synchronize_256.png"))); // NOI18N
        btnAssociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Viagens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLocalidades)
                                .addComponent(jScrollPane1)
                                .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCriar)
                                .addGap(28, 28, 28)
                                .addComponent(btnEliminar)
                                .addGap(40, 40, 40)
                                .addComponent(btnEditar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisar)
                            .addComponent(btnAssociar)
                            .addComponent(btnVoltar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addGap(0, 187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLocalidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEditar)
                                .addComponent(btnVoltar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCriar)
                                .addComponent(btnEliminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAssociar)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
       this.fireInserirViagemClicadoListener();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       this.fireVoltarMenuPrincipalEvent();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAssociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarActionPerformed
        this.fireAssociarViagensClicadoEvent();
    }//GEN-LAST:event_btnAssociarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLocalidades;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}

