/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.ipleiria.tripPlanner.gui.GestaoViagens;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import pt.ipleiria.tripPlanner.gui.GestaoAlojamento.Alojamento;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Etapa;
import pt.ipleiria.tripPlanner.gui.Models.Viagem;
import pt.ipleiria.tripPlanner.gui.events.VisualizarViagensClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.VisualizarViagensClicadoListener;

/**
 *
 * @author DELL
 */
public class VisualizarViagens extends javax.swing.JPanel {

    

    private ArrayList<Etapa> etapasModelList;
    private ArrayList<Alojamento> alojamentosModelList;
    
    private DefaultListModel<Etapa> modelE;
    private DefaultListModel<Alojamento> modelA;
    
    private List<VisualizarViagensClicadoListener> visualizarViagensClicadoListener;

    /**
     * Creates new form InserirEditarViagens
     */
    public VisualizarViagens() {
        initComponents();
        
        etapasModelList = new ArrayList<>();
        alojamentosModelList = new ArrayList<>();
        
        modelE = new DefaultListModel<>();
        modelA = new DefaultListModel<>();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDesignacao = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();
        spListaParticipantes = new javax.swing.JScrollPane();
        lstParticipantes = new javax.swing.JList();
        lblEtapas = new javax.swing.JLabel();
        spListaEtapas = new javax.swing.JScrollPane();
        lstEtapas = new javax.swing.JList();
        lblAlojamentos = new javax.swing.JLabel();
        spListaAlojamentos = new javax.swing.JScrollPane();
        lstAlojamentos = new javax.swing.JList();
        btnOk = new javax.swing.JButton();
        lblTipoViagem = new javax.swing.JLabel();
        lblMostrarDesginacao = new javax.swing.JLabel();
        lblTipoViagemI = new javax.swing.JLabel();
        lblDesignacaoI = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        lblDesignacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDesignacao.setText("Designação:");

        lblParticipantes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblParticipantes.setText("Participantes:");

        lstParticipantes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spListaParticipantes.setViewportView(lstParticipantes);

        lblEtapas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEtapas.setText("Etapas:");

        lstEtapas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spListaEtapas.setViewportView(lstEtapas);

        lblAlojamentos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAlojamentos.setText("Alojamentos:");

        lstAlojamentos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spListaAlojamentos.setViewportView(lstAlojamentos);

        btnOk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnOk.setText("Ok");

        lblTipoViagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTipoViagem.setText("Tipo Viagem:");

        lblTipoViagemI.setText("jLabel1");

        lblDesignacaoI.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTipoViagem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTipoViagemI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDesignacao)
                            .addGap(18, 18, 18)
                            .addComponent(lblDesignacaoI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMostrarDesginacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblParticipantes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(spListaParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEtapas)
                            .addGap(36, 36, 36)
                            .addComponent(spListaEtapas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlojamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spListaAlojamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(289, 289, 289))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesignacao)
                    .addComponent(lblMostrarDesginacao)
                    .addComponent(lblDesignacaoI))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spListaParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParticipantes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoViagem)
                    .addComponent(lblTipoViagemI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEtapas)
                    .addComponent(spListaEtapas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlojamentos)
                    .addComponent(spListaAlojamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblAlojamentos;
    private javax.swing.JLabel lblDesignacao;
    private javax.swing.JLabel lblDesignacaoI;
    private javax.swing.JLabel lblEtapas;
    private javax.swing.JLabel lblMostrarDesginacao;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblTipoViagem;
    private javax.swing.JLabel lblTipoViagemI;
    private javax.swing.JList lstAlojamentos;
    private javax.swing.JList lstEtapas;
    private javax.swing.JList lstParticipantes;
    private javax.swing.JScrollPane spListaAlojamentos;
    private javax.swing.JScrollPane spListaEtapas;
    private javax.swing.JScrollPane spListaParticipantes;
    // End of variables declaration//GEN-END:variables

    public void setDados(Viagem viagem) {
        lblDesignacaoI.setText(DadosAplicacao.getInstance().getViagem(viagem).getDesignacao());
        lblTipoViagemI.setText(DadosAplicacao.getInstance().getViagem(viagem).getTipoViagem());
        
        etapasModelList = DadosAplicacao.getInstance().getViagem(viagem).getEtapas();
        modelE.clear();        
        for (Etapa e : etapasModelList) {
            modelE.addElement(e);
        }
        lstEtapas.setModel(modelE);
        
        alojamentosModelList = DadosAplicacao.getInstance().getViagem(viagem).getAlojamentos();
        modelA.clear();        
        for (Alojamento a : alojamentosModelList) {
            modelA.addElement(a);
        }
        lstAlojamentos.setModel(modelA);
    }
    
}
