package pt.ipleiria.tripPlanner.gui.participantes;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import pt.ipleiria.tripPlanner.gui.Models.DadosAplicacao;
import pt.ipleiria.tripPlanner.gui.Models.Participante;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.ConfirmarClicadoListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ricardo
 */

public class InserirEditarParticipante extends javax.swing.JPanel {
    

    private List<ConfirmarClicadoListener> confirmarClicadoListener;
    /**
     * Creates new form InserirParticipante
     */
    public InserirEditarParticipante() {
        initComponents();
        
        this.confirmarClicadoListener = new ArrayList<>();
    }
    
    public synchronized void addConfirmarClicadoListener(ConfirmarClicadoListener listener){
        this.confirmarClicadoListener.add(listener);
    }
    
    public synchronized void removeConfirmarClicadoListener(ConfirmarClicadoListener listener){
        this.confirmarClicadoListener.remove(listener);
    }

    protected synchronized void fireConfirmarClicadoEvent(){
        for(ConfirmarClicadoListener listener : this.confirmarClicadoListener){
        ConfirmarClicadoEvent evento = new ConfirmarClicadoEvent(this);
        listener.confirmarClicado(evento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLocalidade = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblBI = new javax.swing.JLabel();
        tfLocalidade = new javax.swing.JTextField();
        tfBilheteIdentidade = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblNome = new javax.swing.JLabel();
        cbICF = new javax.swing.JComboBox();
        lblCondicaoFisica = new javax.swing.JLabel();
        lblNomeErro = new javax.swing.JLabel();
        lblDataErro = new javax.swing.JLabel();
        lblBIErro = new javax.swing.JLabel();
        lblLocalidadeErro = new javax.swing.JLabel();
        lblICFErro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbEditor = new javax.swing.JCheckBox();
        cbAdministrador = new javax.swing.JCheckBox();
        panelAdmin = new javax.swing.JPanel();
        pfPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        panelEditor = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPermissoesUtilizador = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPermissoes = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblEditorErro = new javax.swing.JLabel();
        lblAdminErro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        btnOk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnOk.setText("Criar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbEditor.setBackground(new java.awt.Color(255, 255, 255));
        cbEditor.setText("Editor");

        lstPermissoes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel2.setText("Inserir Participantes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));

        lblLocalidade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLocalidade.setText("*Localidade:");

        lblDataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDataNascimento.setText("*Data de Nascimento:");

        lblBI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBI.setText("*Bilhete Identidade:");

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome.setText("*Nome:");

        cbICF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Condição física...", "1", "2", "3", "4", "5" }));

        lblCondicaoFisica.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCondicaoFisica.setText("*Indice Condicao Fisica:");

        lblNomeErro.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLocalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfLocalidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfBilheteIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCondicaoFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbICF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBIErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLocalidadeErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblICFErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblNomeErro)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblDataErro)
                        .addGap(34, 34, 34)
                        .addComponent(lblBIErro)
                        .addGap(40, 40, 40)
                        .addComponent(lblLocalidadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblICFErro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataNascimento)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBI)
                            .addComponent(tfBilheteIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocalidade)
                            .addComponent(tfLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCondicaoFisica)
                            .addComponent(cbICF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Permissões"));

        cbEditor.setBackground(new java.awt.Color(255, 255, 255));
        cbEditor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbEditor.setText("Editor");
        cbEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditorActionPerformed(evt);
            }
        });

        cbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        cbAdministrador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbAdministrador.setText("Administrador");
        cbAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdministradorActionPerformed(evt);
            }
        });

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        panelAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAdmin.setEnabled(false);

        pfPassword.setText("jPasswordField1");
        pfPassword.setEnabled(false);

        lblPassword.setText("Password");
        lblPassword.setEnabled(false);

        tfUsername.setEnabled(false);

        lblUsername.setText("Username");
        lblUsername.setEnabled(false);

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUsername))
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEditor.setBackground(new java.awt.Color(255, 255, 255));
        panelEditor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Permissões de Editor"));
        panelEditor.setEnabled(false);

        lstPermissoesUtilizador.setEnabled(false);
        jScrollPane2.setViewportView(lstPermissoesUtilizador);

        lstPermissoes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Localidades", "Viagens", "Etapas", "Alojamentos", "Participantes" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPermissoes.setEnabled(false);
        jScrollPane1.setViewportView(lstPermissoes);

        jButton1.setText(">>");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditorLayout = new javax.swing.GroupLayout(panelEditor);
        panelEditor.setLayout(panelEditorLayout);
        panelEditorLayout.setHorizontalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEditorErro))
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditorLayout.setVerticalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addGroup(panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditorErro))
                    .addGroup(panelEditorLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAdministrador)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbEditor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdminErro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cbEditor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminErro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnOk)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

       
        if(tfNome.getText() == null){
            lblNomeErro.setText("Introduza um nome!");
            return;
        }
        
        if(jDateChooser2 == null){
            lblDataErro.setText("Introduza uma Data de Nascimento!");
            return;
        }
        
        if(tfBilheteIdentidade.getText() == null){
            lblBIErro.setText("Introduza um BI!");
            return;
        }
        
        for(Participante participante: DadosAplicacao.getInstance().getParticipantes()){
            if(tfBilheteIdentidade.getText().equals(participante.getBI() + "")){
                lblBIErro.setText("BI já existente!");
                return;
            }
        }
        
        if(tfLocalidade.getText() == null){
            lblLocalidadeErro.setText("Insira uma Localidade!");
            return;
        }
        
        if(cbICF.getSelectedIndex()<1){
            lblICFErro.setText("Escolha um ");
            return;      
        }
        
        if(cbAdministrador.isSelected()){
            if(tfUsername.getText() == null){
            lblAdminErro.setText("Introduza um username!");
            return;
            }
            
            for(Participante participante: DadosAplicacao.getInstance().getParticipantes()){
                if(tfUsername.getText().equals(participante.getUsername())){
                    lblAdminErro.setText("Já existe um participante com o Username introduzido!");
                    return;
                }
            }
        
            
            if(pfPassword.getPassword() == null){
            lblAdminErro.setText("Introduza uma password!");
            return;
            }
        }
        
        boolean editor = false;
        
        if(cbEditor.isSelected()){
            if(lstPermissoesUtilizador.getSelectedValuesList().isEmpty()){
            lblEditorErro.setText("Escolha pelo menos uma permissão de editor!");
            return;
            }
            editor=true;
        }
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dataNasc = formatter.format(jDateChooser2.getCalendar().getTime());
        
        Participante participante;   
        if(cbAdministrador.isSelected()){
            participante = new Participante(tfNome.getText(), jDateChooser2.getCalendar(), Integer.parseInt(tfBilheteIdentidade.getText()), tfLocalidade.getText(), Integer.parseInt(cbICF.getModel().getElementAt(cbICF.getSelectedIndex()).toString()), true, tfUsername.getText(), pfPassword.getPassword(), editor, (ArrayList<String>)lstPermissoesUtilizador.getSelectedValuesList(), false);
            DadosAplicacao.getInstance().adicionarParticipante(participante);
        }else{
            participante = new Participante(tfNome.getText(), jDateChooser2.getCalendar(), Integer.parseInt(tfBilheteIdentidade.getText()), tfLocalidade.getText(), Integer.parseInt(cbICF.getModel().getElementAt(cbICF.getSelectedIndex()).toString()), false, tfBilheteIdentidade.getText(), dataNasc.toCharArray(), editor, (ArrayList<String>)lstPermissoesUtilizador.getSelectedValuesList(), true);
            DadosAplicacao.getInstance().adicionarParticipante(participante);
        }

        JOptionPane.showMessageDialog(this, "Utilizador Inserido!");
        
        this.fireConfirmarClicadoEvent();
        
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void cbAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdministradorActionPerformed
       panelAdmin.setEnabled(cbAdministrador.isEnabled());
       lblPassword.setEnabled(cbAdministrador.isEnabled());
       lblUsername.setEnabled(cbAdministrador.isEnabled());
       tfUsername.setEnabled(cbAdministrador.isEnabled());
       pfPassword.setEnabled(cbAdministrador.isEnabled());
       if(!cbAdministrador.isEnabled()){
           tfUsername.setText("");
           pfPassword.setText("");
       }
    }//GEN-LAST:event_cbAdministradorActionPerformed
                                       
    private void cbEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditorActionPerformed
        panelEditor.setEnabled(cbEditor.isEnabled());
        jButton1.setEnabled(cbEditor.isEnabled());
        jButton2.setEnabled(cbEditor.isEnabled());
        jButton3.setEnabled(cbEditor.isEnabled());
        jButton4.setEnabled(cbEditor.isEnabled());
        lstPermissoes.setEnabled(cbEditor.isEnabled());
        lstPermissoesUtilizador.setEnabled(cbEditor.isEnabled());
        if(lstPermissoesUtilizador.getModel().getSize() > 0){
        DefaultListModel<String> model;
        model = (DefaultListModel<String>) lstPermissoesUtilizador.getModel();
        lstPermissoesUtilizador.removeAll();
        if(lstPermissoes.getModel().getSize() > 0){
            for(int i=0; i<=lstPermissoes.getModel().getSize(); i++){
              String permissaoUtilizador = (String) lstPermissoes.getModel().getElementAt(i);
              model.addElement(permissaoUtilizador);
            }
            lstPermissoes.setModel(model);
        }else{
            lstPermissoes.setModel(model);
        }
        }
        
    }//GEN-LAST:event_cbEditorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel<String> model =  new DefaultListModel<>();
        model = (DefaultListModel<String>) lstPermissoes.getModel();
        lstPermissoes.removeAll();
        if(lstPermissoesUtilizador.getModel().getSize() > 0){
            for(int i=0; i<=lstPermissoesUtilizador.getModel().getSize(); i++){
              String permissaoUtilizador = (String) lstPermissoesUtilizador.getModel().getElementAt(i);
              model.addElement(permissaoUtilizador);
            }
            lstPermissoesUtilizador.setModel(model);
        }else{
           lstPermissoesUtilizador.setModel(model);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultListModel<String> model =  new DefaultListModel<>();
        model.addElement((String) lstPermissoes.getSelectedValue());
        lstPermissoes.remove(lstPermissoes.getSelectedIndex());
        lstPermissoes.repaint();
        if(lstPermissoesUtilizador.getModel().getSize() > -1){
            for(int i=0; i<=lstPermissoesUtilizador.getModel().getSize(); i++){
              String permissaoUtilizador = (String) lstPermissoesUtilizador.getModel().getElementAt(i);
              model.addElement(permissaoUtilizador);
            }
            lstPermissoesUtilizador.setModel(model);
            lstPermissoesUtilizador.repaint();
        }else{
            lstPermissoesUtilizador.setModel(model);
            lstPermissoesUtilizador.repaint();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultListModel<String> model =  new DefaultListModel<>();
        model = (DefaultListModel<String>) lstPermissoesUtilizador.getModel().getElementAt(lstPermissoesUtilizador.getSelectedIndex());
        lstPermissoesUtilizador.remove(lstPermissoesUtilizador.getSelectedIndex());
        if(lstPermissoes.getModel().getSize() > 0){
            for(int i=0; i<=lstPermissoes.getModel().getSize(); i++){
              String permissaoUtilizador = (String) lstPermissoes.getModel().getElementAt(i);
              model.addElement(permissaoUtilizador);
            }
            lstPermissoes.setModel(model);
        }else{
            lstPermissoes.setModel(model);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel<String> model =  new DefaultListModel<>();
        model = (DefaultListModel<String>) lstPermissoesUtilizador.getModel();
        lstPermissoesUtilizador.removeAll();
        if(lstPermissoes.getModel().getSize() > 0){
            for(int i=0; i<=lstPermissoes.getModel().getSize(); i++){
              String permissaoUtilizador = (String) lstPermissoes.getModel().getElementAt(i);
              model.addElement(permissaoUtilizador);
            }
            lstPermissoes.setModel(model);
        }else{
            lstPermissoes.setModel(model);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         this.fireConfirmarClicadoEvent();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox cbAdministrador;
    private javax.swing.JCheckBox cbEditor;
    private javax.swing.JComboBox cbICF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdminErro;
    private javax.swing.JLabel lblBI;
    private javax.swing.JLabel lblBIErro;
    private javax.swing.JLabel lblCondicaoFisica;
    private javax.swing.JLabel lblDataErro;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEditorErro;
    private javax.swing.JLabel lblICFErro;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblLocalidadeErro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeErro;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JList lstPermissoes;
    private javax.swing.JList lstPermissoesUtilizador;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfBilheteIdentidade;
    private javax.swing.JTextField tfLocalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
