package pt.ipleiria.tripPlanner.gui.participantes;

import java.util.ArrayList;
import java.util.List;
import pt.ipleiria.tripPlanner.gui.events.EditarParticipantesClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.EditarParticipantesClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.InserirParticipantesClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.InserirParticipantesClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.VisualizarParticipantesClicadoEvent;
import pt.ipleiria.tripPlanner.gui.events.VisualizarParticipantesClicadoListener;
import pt.ipleiria.tripPlanner.gui.events.VoltarMenuPrincipalEvent;
import pt.ipleiria.tripPlanner.gui.events.VoltarMenuPrincipalListener;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ricardo
 */
public class MenuParticipantes extends javax.swing.JPanel {

    private List<InserirParticipantesClicadoListener> inserirParticipantesClicadoListener;
    private List<EditarParticipantesClicadoListener> editarParticipantesClicadoListener;
    private List<VisualizarParticipantesClicadoListener> visualizarParticipantesClicadoListener;
    private List<VoltarMenuPrincipalListener> voltarMenuPrincipalListener;
    /**
     * Creates new form MenuParticipantes
     */
    public MenuParticipantes() {
        initComponents();
        
        this.inserirParticipantesClicadoListener = new ArrayList<>();
        this.editarParticipantesClicadoListener = new ArrayList<>();
        this.visualizarParticipantesClicadoListener = new ArrayList<>();
        this.voltarMenuPrincipalListener = new ArrayList<>();
    }

    public synchronized void addInserirParticipantesClicadoListener(InserirParticipantesClicadoListener listener){
        this.inserirParticipantesClicadoListener.add(listener);
    }
    
    public synchronized void removeInserirParticipantesClicadoListener(InserirParticipantesClicadoListener listener){
        this.inserirParticipantesClicadoListener.remove(listener);
    }

    protected synchronized void fireInserirParticipantesClicadoEvent(){
        for(InserirParticipantesClicadoListener listener : this.inserirParticipantesClicadoListener){
        InserirParticipantesClicadoEvent evento = new InserirParticipantesClicadoEvent(this);
        listener.InserirParticipantesClicado(evento);
        }
    }
    
    public synchronized void addEditarParticipantesClicadoListener(EditarParticipantesClicadoListener listener){
        this.editarParticipantesClicadoListener.add(listener);
    }
    
    public synchronized void removeEditarParticipantesClicadoListener(EditarParticipantesClicadoListener listener){
        this.editarParticipantesClicadoListener.remove(listener);
    }

    protected synchronized void fireEditarParticipantesClicadoEvent(){
        for(EditarParticipantesClicadoListener listener : this.editarParticipantesClicadoListener){
        EditarParticipantesClicadoEvent evento = new EditarParticipantesClicadoEvent(this);
        listener.EditarParticipantesClicado(evento);
        }
    }
    
    public synchronized void addVisualizarParticipantesClicadoListener(VisualizarParticipantesClicadoListener listener){
        this.visualizarParticipantesClicadoListener.add(listener);
    }
    
    public synchronized void removeVisualizarParticipantesClicadoListener(VisualizarParticipantesClicadoListener listener){
        this.visualizarParticipantesClicadoListener.remove(listener);
    }

    protected synchronized void fireVisualizarParticipantesClicadoEvent(){
        for(VisualizarParticipantesClicadoListener listener : this.visualizarParticipantesClicadoListener){
        VisualizarParticipantesClicadoEvent evento = new VisualizarParticipantesClicadoEvent(this);
        listener.visualizarParticipantesClicado(evento);
        }
    }
    
    public synchronized void addVoltarMenuPrincipalListener(VoltarMenuPrincipalListener listener){
        this.voltarMenuPrincipalListener.add(listener);
    }
    
    public synchronized void removeVoltarMenuPrincipalListener(VoltarMenuPrincipalListener listener){
        this.voltarMenuPrincipalListener.remove(listener);
    }

    protected synchronized void fireVoltarMenuPrincipalEvent(){
        for(VoltarMenuPrincipalListener listener : this.voltarMenuPrincipalListener){
        VoltarMenuPrincipalEvent evento = new VoltarMenuPrincipalEvent(this);
        listener.voltarMenuPrincipal(evento);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPesquisar = new javax.swing.JTextField();
        spListaParticipantes = new javax.swing.JScrollPane();
        lstPesquisa = new javax.swing.JList();
        btnVisualizar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblParticipantes = new javax.swing.JLabel();
        lblLocalidades = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tfPesquisar.setText("Pesquisar");

        lstPesquisa.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        spListaParticipantes.setViewportView(lstPesquisa);

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/lupa.png"))); // NOI18N
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/Inserir1.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/eliminar1.png"))); // NOI18N

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/tripPlanner/gui/Imagens/back-trans.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblParticipantes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblParticipantes.setText("Participantes");

        lblLocalidades.setText("Participantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblParticipantes)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLocalidades)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemover)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(spListaParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisualizar)
                            .addComponent(btnVoltar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLocalidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisualizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spListaParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemover)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdicionar)
                                .addComponent(btnVoltar)))
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        this.fireInserirParticipantesClicadoEvent();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.fireEditarParticipantesClicadoEvent();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        this.fireVisualizarParticipantesClicadoEvent();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.fireVoltarMenuPrincipalEvent();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblLocalidades;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JList lstPesquisa;
    private javax.swing.JScrollPane spListaParticipantes;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
