/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pt.ipleiria.tripPlanner.gui.GestaoLocalidades;

/**
 *
 * @author DELL
 */
public class MostrarLocalidade extends javax.swing.JPanel {

    /**
     * Creates new form CriarEditarLocalidade
     */
    public MostrarLocalidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDesignacao = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        lblAlojamento = new javax.swing.JLabel();
        spAlojamento = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbOk = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        lblDesignacaoMostrar = new javax.swing.JLabel();
        lblMostrarLongitude = new javax.swing.JLabel();
        lblMostrarLatitude = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDesignacao.setText("Designação:");

        lblGPS.setText("GPS:");

        lblLongitude.setText("Long:");

        lblLatitude.setText("Lat:");

        lblAlojamento.setText("Alojamento");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        spAlojamento.setViewportView(jTextArea1);

        jbOk.setText("Ok");

        jbCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spAlojamento, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lblAlojamento)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesignacao)
                            .addComponent(lblGPS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLongitude)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMostrarLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblLatitude)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMostrarLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDesignacaoMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbOk)
                .addGap(18, 18, 18)
                .addComponent(jbCancelar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesignacao)
                    .addComponent(lblDesignacaoMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPS)
                    .addComponent(lblLongitude)
                    .addComponent(lblLatitude)
                    .addComponent(lblMostrarLongitude)
                    .addComponent(lblMostrarLatitude))
                .addGap(53, 53, 53)
                .addComponent(lblAlojamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spAlojamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel lblAlojamento;
    private javax.swing.JLabel lblDesignacao;
    private javax.swing.JLabel lblDesignacaoMostrar;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblMostrarLatitude;
    private javax.swing.JLabel lblMostrarLongitude;
    private javax.swing.JScrollPane spAlojamento;
    // End of variables declaration//GEN-END:variables
}
